### ISSUE TITLE
reduce size: remove lib/libgdal.a

### ISSUE THREAD

**Issue by visr** [JuliaGeo/GDALBuilder#4]
Quoting @tshort from discourse https://discourse.julialang.org/t/package-size-crazziness/14644/18
> In the Win64 GDAL library built by GDALBuilder, an easy way to trim size is to remove lib/libgdal.a (159 MB out of 314 MB).

**Comment by tshort** [comment]
Just to confirm this, I asked if there's any reason not to delete `lib/*.a` files on the bindeps2 Slack channel. Elliot responded: 

> Only if you want to support someone else compiling against the static library in the future. 
> Feel free to delete that within your buildscript if that isn’t part of what you want to support.

Also, this isn't just Windows. All platforms include `lib/*.a` files.

**Comment by visr** [comment]
Ok, thanks for checking! I don't see how or why to support that now, so I guess this would be good to remove.
